chore(update): Move apiVersion to apps/v1
With k8s 1.21 the deployment apiVersion supported is apps/v1 and the
extensions/v1beta1 is deprecated, thus the installation of the chart
fails with:

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

This update fixes it and the chart can be installed.